/* src/utils/glossary.js */
export const TERMINOLOGY = {
  BOOT: {
    KERNEL: "INITIALIZING KERNEL...",
    MARKET: "LOADING MARKET PROTOCOLS...",
    SECURE: "ESTABLISHING SECURE CONNECTION...",
    ASSETS: "DECRYPTING ASSETS...",
    GRANTED: "ACCESS GRANTED."
  },
  GENERAL: {
    MODULES: "MAIN MODULES",
    SAVE: "SAVE PROGRESS",
    CLOSE: "CLOSE FILE",
    FINALIZE: "FINALIZE PROTOCOL",
    CANCEL: "CANCEL",
    CREATE: "CREATE",
    ADD: "ADD",
    ANALYZE: "ANALYZE",
    ID_LABEL: "PROJECT ID"
  },
  FINANCE: {
    HEADER: "PROFIT MATRIX",
    SUBTITLE: "FINANCIAL HEALTH & REAL MARGINS",
    TREND: "REVENUE TREND",
    LEDGER: "TRANSACTION LEDGER",
    LOG: "LOG TRANSACTION"
  },
  WORKSHOP: {
    HUB_HEADER: "WORKSHOP",
    HUB_SUBTITLE: "R&D OPERATIONS",
    ACTIVE_OPS: "ACTIVE OPERATIONS",
    DRAFTS: "CONCEPT BLUEPRINTS",
    NEW_PROJECT: "NEW PROJECT",
    VAULT_HEADER: "THE VAULT",
    VAULT_SUBTITLE: "ARCHIVED & HALTED",
    MISSIONS_HEADER: "OPERATIONAL MILESTONES",
    BOM_HEADER: "RESOURCE ALLOCATION",
    NOTES_LABEL: "TECHNICAL LOGS",
    TAGS_LABEL: "SYSTEM TAGS",
    CALIBRATION: "MARKET CALIBRATION",
    TARGET_RETAIL: "TARGET RETAIL",
    UNIT_COST: "UNIT COST",
    PROJ_MARGIN: "PROJ. MARGIN",
    REF_VISUAL: "REFERENCE VISUAL",
    STUDIO_LABEL: "STUDIO INTERFACE",
    ID_PREFIX: "PROTO-ID"
  },
  INVENTORY: {
    HEADER: "SUPPLY LOCKER",
    MANIFEST_LABEL: "MATERIAL MANIFEST",
    ASSET_DETAILS: "ASSET DETAILS",
    RESTOCK: "RESTOCK / UPDATE",
    INTAKE: "NEW ASSET INTAKE",
    HISTORY_LOG: "PURCHASE HISTORY LOG",
    NOTIFICATIONS: "NOTIFICATIONS"
  },
  MARKET: {
    HEADER: "MARKET RADAR",
    SUBTITLE: "COMPETITIVE INTELLIGENCE",
    PULSE_HEADER: "MARKET PULSE",
    AVG_PRICE: "AVG MARKET PRICE",
    TARGET: "TRACK NEW TARGET",
    SCANNING: "SCANNING FREQUENCIES..."
  }
};